name: SnykSCAScan
on: push

jobs: 
  run-SnykScan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      # will take the replica of the workspace and do the scan in the checkout folder and not on our master branch
      - name: Snyk
      # You may pin to the exact commit or the version.
      # uses: snyk/actions@b98d498629f1c368650224d6d212bf7dfa89e4bf
        uses: snyk/actions@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          
        # with:
        #   # Which Snyk command to run, defaults to test
        #   command: # optional, default is test
        #   # Additional arguments to pass to Snyk
        #   args: # optional
        #   # Output a snyk.json file with results if running the test command
        #   json: # optional
          
